### ISSUE TITLE
Weird look of JideTabbedPane using PlasticXPLookAndFeel

### ISSUE THREAD

**Issue by blerins** [jidesoft/jide-oss#11]
Hi,

I'm using JideTabbedPane in a application with PlasticXPLookAndFeel, I would like to use flat shape for tabs but when you set `JideTabbedPane.defaultTabShape` to `SHAPE_FLAT` the result is really weird:

![bad_jide](https://cloud.githubusercontent.com/assets/3084794/9933407/f5f95fe0-5d4a-11e5-9c40-95a092dc994d.png)

If `JideTabbedPane.defaultTabShape` isn't set, it gets well rendered:

![good_jide](https://cloud.githubusercontent.com/assets/3084794/9933424/112a254c-5d4b-11e5-924a-d88f3b4910c7.png)

I'm using [jide-oss 3.6.10](http://search.maven.org/#artifactdetails%7Ccom.jidesoft%7Cjide-oss%7C3.6.10%7Cjar) and [jgoodies-looks 2.7.0](http://search.maven.org/#artifactdetails%7Ccom.jgoodies%7Cjgoodies-looks%7C2.7.0%7Cjar)

Thanks!!

**Comment by jidesoft** [comment]
The screenshot doesn't look like SHAPE_FLAT. The flat style has a rectangular shape, no curve.

**Comment by blerins** [comment]
Thats just the problem, tabs are padded to the left, but they still are
painted with round corners. And borders get fat and black.

Can you know watching the picture what may I be doing wrong?

My code is currently JRuby, but I may try to provide some Java failing code.

Thanks!

**Comment by jidesoft** [comment]
This site doesn't allow me to attached picture. Or I will attach a picture of what flat style looks like. However you can run JideTabbedPaneDemo to see it yourself. It is part of the JIDE evaluation that is available to download for free from our website.

**Comment by blerins** [comment]
Excuse me if I'm not able to explain me too well. I know what flat style
looks, if I inherit PlasticXPLookAndFeel jide tabbed pane behaves well, but
if I use it directly, it looks like the attached picture and I want flat
style tabs. It seems that jide does a extrange management of plastic look
and feel.

Thanks!

**Comment by jidesoft** [comment]
I am sorry but I still didn't get your question. Please include a test case so that I can reproduce the issue. Please also email support@jidesoft.com for technical support from now on.

**Comment by blerins** [comment]
It happens that setting the default shape through UIManager doesn't works with JRuby.

That Java code behaves well:

```Java
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import com.jgoodies.looks.plastic.PlasticXPLookAndFeel;
import com.jidesoft.swing.JideTabbedPane;

public class JideBug {
  public static void main(final String[] args) {
    try {
      UIManager.setLookAndFeel(new PlasticXPLookAndFeel());
    }
    catch ( UnsupportedLookAndFeelException e) {
    }
    UIManager.getDefaults().put("JideTabbedPane.defaultTabShape", JideTabbedPane.SHAPE_FLAT);
    JFrame window = new JFrame();
    JideTabbedPane tabs = new JideTabbedPane();
    tabs.addTab("Bug", new JPanel());
    tabs.addTab("Bug2", new JPanel());
    window.add(tabs);
    window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    window.setSize(400, 400);
    window.setVisible(true);
  }
}
```

While that JRuby code doesn't:

```JRuby
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import com.jgoodies.looks.plastic.PlasticXPLookAndFeel;
import com.jidesoft.swing.JideTabbedPane;

UIManager.setLookAndFeel(PlasticXPLookAndFeel.new());
UIManager.getDefaults().put("JideTabbedPane.defaultTabShape", JideTabbedPane::SHAPE_FLAT);
window = JFrame.new();
tabs = JideTabbedPane.new();
tabs.addTab("Bug", JPanel.new());
tabs.addTab("Bug2", JPanel.new());
window.add(tabs);
window.setDefaultCloseOperation(JFrame::EXIT_ON_CLOSE);
window.setSize(400, 400);
window.setVisible(true);
```

Finally I discovered that `JideTabbedPane.setTabShape` behaves always fine.

Thanks!!

**Comment by jidesoft** [comment]
I see. You should always use setTabShape in this case. You could change UIDefault but it should be done using a different way by using UIDefaultCustomizer. 

LookAndFeelFactory.addUIDefaultCustomizer(...);
UIManager.setLookAndFeel
LookAndFeelFactory.installJideExtension();
