### ISSUE TITLE
sources-jar not readable on Linux

### ISSUE THREAD

**Issue by jschneider** [jidesoft/jide-oss#14]
When I am extracting the sources jar using Ubuntu 16.04, I can not open the source files.
This seems to be caused by missing rights on the java files.

I have honestly no idea how this might have happened. But it seems to be the case.

**Comment by jidesoft** [comment]
I am not quite sure about it either. We didn't do anything special for Ubuntu. Can you chmod on your machine for these files?

**Comment by jschneider** [comment]
It does not depend on Ubuntu. It is a problem (at least I think it is) within the sources.jar file.
I have downloaded it from maven central:
https://search.maven.org/remotecontent?filepath=com/jidesoft/jide-oss/3.6.14/jide-oss-3.6.14-sources.jar

When extracting this jar file, the source files can not be read due to permission problems.
I can reproduce this using "file-roller" or "unzip"

**Comment by jidesoft** [comment]
The source and release jars are both built by maven plugin which we don't have control anyway. You don't need to unzip the source jar. I usually just link the source jar to the lib jar in the Java IDE so that I can open the source code directly in Java IDE.
