### ISSUE TITLE
Fix unchecked/rawtypes API usage

### ISSUE THREAD

**Issue by trejkaz** [jidesoft/jide-oss#15]
`JComboBox`, `JList`, `ListModel`, `ComboBoxModel`, and probably a lot of other classes gained generic parameters at some point after Java added generics. Usage of these now shows warnings if you omit the parameter.

I'm trying to remove these warnings from our code, but a large number of these are coming from things we're using in JIDE.

For instance, if we extend `JideComboBox`, we get warnings when we use methods on the class.

    setPrototypeDisplayValue("an example value");

Would give the warning:

    Unchecked call to 'setPrototypeDisplayValue(E)' as a member of raw type 'javax.swing.JComboBox'

To fix this, `JideComboBox` should add the `<E>` parameter that its superclass possesses, so that subclasses of it can add the parameter. The same goes for any subclasses of that class, and so forth, parameters to methods, and potentially other things.

**Comment by jidesoft** [comment]
Right now, our source code is still compatible with -source 1.6 which is why we haven't added the generic. At some time, we will support -source 1.7. At that time, we will add generic in. For now you can mute all the warnings from JIDE.

**Comment by trejkaz** [comment]
There's no actual way to suppress all the warnings this causes at the current point in time, without muting other legitimate issues that I don't want to suppress. If there were, I would already be doing it.

I don't think that supporting Java 6 is worthwhile at this point in time anyway, considering that even Java 7 is no longer supported. Everyone at this point in time should be targeting Java 8, and probably even getting ready for Java 9. Which reminds me, JIDE has a few violations for that as well. I suppose if I file those, you won't accept those either. So is it easier to just drop JIDE? Maybe...

**Comment by jidesoft** [comment]
You just can't believe how our users are lagging behind in term of the JDK versions. Anyway, it will be done. JDK9 will be supported as well.
