### ISSUE TITLE
Java 11 compatibility

### ISSUE THREAD

**Issue by prabodh1194** [jidesoft/jide-oss#33]
Java fx has been moved out of java 11's runtime. Will this affect jidesoft?

https://github.com/jidesoft/jide-oss/blob/11c9dbf226dc2500c27d86a0df3963b091f5406e/src/com/jidesoft/swing/JideButton.java#L13

**Comment by jidesoft** [comment]
No. We didn’t use any JavaFX code in our Swing based products. 

 

Thanks,

-David
