### ISSUE TITLE
jide-oss Java 11 Compatibility

### ISSUE THREAD

**Issue by marioradev** [jidesoft/jide-oss#35]
Hi experts,

Are you planning to release a jide-oss version which is compatible with Java 11? If yes, when do you expect this will happen?
The jdeps report is complaining:
jide-oss-3.3.4.jar -> JDK removed internal API jide-oss-3.3.4.jar -> java.base jide-oss-3.3.4.jar -> java.desktop com.jidesoft.plaf.LookAndFeelFactory -> com.sun.java.swing.plaf.windows.WindowsLookAndFeel JDK internal API (JDK removed internal API) com.jidesoft.plaf.UIDefaultsLookup -> sun.reflect.Reflection JDK internal API (JDK removed internal API) com.jidesoft.plaf.aqua.AquaJidePopupMenuUI -> apple.laf.AquaPopupMenuUI JDK internal API (JDK removed internal API) com.jidesoft.plaf.aqua.AquaRangeSliderUI -> apple.laf.AquaSliderUI JDK internal API (JDK removed internal API) com.jidesoft.plaf.aqua.AquaRangeSliderUI -> apple.laf.JRSUIConstants JDK internal API (JDK removed internal API) com.jidesoft.plaf.aqua.AquaRangeSliderUI -> apple.laf.JRSUIConstants$Orientation JDK internal API (JDK removed internal API) com.jidesoft.plaf.aqua.AquaRangeSliderUI -> apple.laf.JRSUIConstants$State JDK internal API (JDK removed internal API) com.jidesoft.plaf.basic.BasicFolderChooserUI -> sun.awt.shell.ShellFolder JDK internal API (java.desktop) com.jidesoft.plaf.basic.BasicJideSplitButtonUI -> com.sun.java.swing.plaf.windows.WindowsLookAndFeel JDK internal API (JDK removed internal API) com.jidesoft.plaf.basic.BasicPainter -> com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel JDK internal API (JDK removed internal API) com.jidesoft.plaf.basic.BasicPainter -> com.sun.java.swing.plaf.windows.WindowsLookAndFeel JDK internal API (JDK removed internal API) com.jidesoft.plaf.basic.BasicPainter -> sun.swing.plaf.synth.SynthIcon JDK internal API (JDK removed internal API) com.jidesoft.plaf.basic.BasicStyledLabelUI -> com.sun.java.swing.plaf.windows.WindowsLookAndFeel JDK internal API (JDK removed internal API) com.jidesoft.plaf.eclipse.EclipseMenuItemUI -> com.sun.java.swing.plaf.windows.WindowsGraphicsUtils JDK internal API (JDK removed internal API) com.jidesoft.plaf.eclipse.EclipseMenuItemUI -> com.sun.java.swing.plaf.windows.WindowsLookAndFeel JDK internal API (JDK removed internal API) com.jidesoft.plaf.eclipse.EclipseMenuUI -> com.sun.java.swing.plaf.windows.WindowsGraphicsUtils JDK internal API (JDK removed internal API) com.jidesoft.plaf.eclipse.EclipseMenuUI -> com.sun.java.swing.plaf.windows.WindowsLookAndFeel JDK internal API (JDK removed internal API) com.jidesoft.plaf.metal.MetalUtils$GradientPainter -> sun.swing.CachedPainter JDK internal API (java.desktop) com.jidesoft.plaf.vsnet.VsnetMenuItemUI -> com.sun.java.swing.plaf.windows.WindowsGraphicsUtils JDK internal API (JDK removed internal API) com.jidesoft.plaf.vsnet.VsnetMenuItemUI -> com.sun.java.swing.plaf.windows.WindowsLookAndFeel JDK internal API (JDK removed internal API) com.jidesoft.plaf.vsnet.VsnetMenuUI -> com.sun.java.swing.plaf.windows.WindowsGraphicsUtils JDK internal API (JDK removed internal API) com.jidesoft.plaf.vsnet.VsnetMenuUI -> com.sun.java.swing.plaf.windows.WindowsLookAndFeel JDK internal API (JDK removed internal API) com.jidesoft.plaf.vsnet.VsnetWindowsProgressBarUI -> com.sun.java.swing.plaf.windows.WindowsProgressBarUI JDK internal API (JDK removed internal API) com.jidesoft.plaf.windows.AnimationController -> com.sun.java.swing.plaf.windows.WindowsLookAndFeel JDK internal API (JDK removed internal API) com.jidesoft.plaf.windows.AnimationController -> sun.awt.AppContext JDK internal API (java.desktop) com.jidesoft.plaf.windows.AnimationController -> sun.security.action.GetBooleanAction JDK internal API (java.base) com.jidesoft.plaf.windows.AnimationController$PartUIClientPropertyKey -> sun.swing.UIClientPropertyKey JDK internal API (JDK removed internal API) com.jidesoft.plaf.windows.TMSchema$State -> sun.awt.windows.ThemeReader JDK internal API (JDK removed internal API) com.jidesoft.plaf.windows.WindowsJidePopupMenuUI -> com.sun.java.swing.plaf.windows.WindowsPopupMenuUI JDK internal API (JDK removed internal API) com.jidesoft.plaf.windows.WindowsRangeSliderUI -> com.sun.java.swing.plaf.windows.WindowsSliderUI JDK internal API (JDK removed internal API) com.jidesoft.plaf.windows.XPStyle -> com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel JDK internal API (JDK removed internal API) com.jidesoft.plaf.windows.XPStyle -> sun.awt.windows.ThemeReader JDK internal API (JDK removed internal API) com.jidesoft.plaf.windows.XPStyle -> sun.security.action.GetPropertyAction JDK internal API (java.base) com.jidesoft.plaf.windows.XPStyle$Skin -> sun.awt.windows.ThemeReader JDK internal API (JDK removed internal API) com.jidesoft.plaf.windows.XPStyle$SkinPainter -> sun.awt.image.CachingSurfaceManager JDK internal API (JDK removed internal API) com.jidesoft.plaf.windows.XPStyle$SkinPainter -> sun.awt.image.SunWritableRaster JDK internal API (java.desktop) com.jidesoft.plaf.windows.XPStyle$SkinPainter -> sun.awt.image.SurfaceManager JDK internal API (java.desktop) com.jidesoft.plaf.windows.XPStyle$SkinPainter -> sun.awt.windows.ThemeReader JDK internal API (JDK removed internal API) com.jidesoft.plaf.windows.XPStyle$SkinPainter -> sun.swing.CachedPainter JDK internal API (java.desktop) com.jidesoft.plaf.windows.XPStyle$XPStatefulFillBorder -> com.sun.java.swing.plaf.windows.WindowsComboBoxUI JDK internal API (JDK removed internal API) com.jidesoft.plaf.xerto.XertoJideButtonUI -> com.sun.java.swing.plaf.windows.WindowsButtonUI JDK internal API (JDK removed internal API) com.jidesoft.popup.JidePopup -> sun.awt.EmbeddedFrame JDK internal API (java.desktop) com.jidesoft.swing.TristateCheckBoxIcon -> sun.swing.plaf.synth.SynthIcon JDK internal API (JDK removed internal API) JDK Internal API Suggested Replacement ---------------- --------------------- sun.reflect.Reflection Use java.lang.StackWalker @since 9 sun.security.action.GetBooleanAction Use java.security.PrivilegedAction @since 1.1 sun.security.action.GetPropertyAction Use java.security.PrivilegedAction @since 1.1

Thanks in advance for the reply.

Regards, 
Mario

**Comment by ViktorValkov** [comment]
@jidesoft  Can you please make it a bit more clear what does "add-export jvm parameters" means or referance some material that explain it.

**Comment by jidesoft** [comment]
Please see details at http://www.jidesoft.com/forum/viewtopic.php?f=8&t=16774

**Comment by marioradev** [comment]
Hi,
@jidesoft I have registered in forum and the admin activated my account but I see the following message in when I try to open the topic:

> Information
> You are not authorised to read this forum.

Can you advice me what I can do?
Regards, Mario

**Comment by jidesoft** [comment]
You should have access now. It is for customer only. 

 

Thanks,

-David
