### ISSUE TITLE
java 11 warning: Illegal reflective access

### ISSUE THREAD

**Issue by sda399** [jidesoft/jide-oss#41]
Hi, I got this warning when starting my app using jdk11.

jide: 3.7.1
os: ubuntu LTS 18.04.3
java: openjdk version "11.0.4" (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)

```
WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by com.jidesoft.swing.JideTabbedPane (file:/home/.../com/jidesoft/jide-common/3.7.1/jide-common-3.7.1.jar) to field javax.swing.JTabbedPane.visComp
WARNING: Please consider reporting this to the maintainers of com.jidesoft.swing.JideTabbedPane
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

https://github.com/jidesoft/jide-oss/blob/7766bd0dd65338534eb41c5e8dbcd067c7ebec17/src/com/jidesoft/swing/JideTabbedPane.java#L1196

**Comment by jidesoft** [comment]
Unfortunately, it will remain there. There is no way to workaround it.
